# Generated by Django 2.1.1 on 2022-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcalc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_file', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
