# Generated by Django 2.1.5 on 2022-11-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcalc', '0003_defaultfile_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDefaultDatasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouping_method', models.CharField(blank=True, choices=[('frequency', 'Frequency'), ('audience', 'Audience'), ('language', 'Language')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadtrain',
            name='default_training_file',
            field=models.CharField(blank=True, choices=[('english_training_data.txt', 'CMU English'), ('english_training_data_onlyA.txt', 'CMU English A'), ('small_cmu_frequencies.txt', 'CMU English with Freqs')], max_length=200),
        ),
    ]
