# Generated by Django 2.1.7 on 2022-05-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcalc', '0003_auto_20220424_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadWithDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_file', models.CharField(choices=[('english_training_data.txt', 'english_training_data.txt'), ('english_training_data_onlyA.txt', 'english_training_data_onlyA.txt')], max_length=200)),
                ('test_file', models.FileField(upload_to='uploads')),
                ('training_model', models.CharField(choices=[('unigram', 'Unigram Probability'), ('bigram', 'Bigram Probability'), ('posUnigram', 'Positional Unigram Score'), ('posBigram', 'Positional Bigram Score')], max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadtrain',
            name='test_file',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='uploadtrain',
            name='training_file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
