# Generated by Django 4.1.4 on 2024-12-13 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcalc', '0004_uploadtrain_current_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtrain',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
