# Generated by Django 2.1.7 on 2022-05-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcalc', '0004_auto_20220505_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtrain',
            name='default_training_file',
            field=models.CharField(blank=True, choices=[('english_training_data.txt', 'english_training_data.txt'), ('english_training_data_onlyA.txt', 'english_training_data_onlyA.txt')], max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadtrain',
            name='training_file',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
