# Generated by Django 4.1.4 on 2024-12-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcalc', '0006_alter_uploadtrain_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtrain',
            name='current_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
