# Generated by Django 4.1.4 on 2024-12-13 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcalc', '0007_alter_uploadtrain_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtrain',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
