# Generated by Django 2.1.5 on 2022-05-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webcalc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defaultfile",
            name="short_desc",
        ),
    ]
