# Generated by Django 4.1.4 on 2024-12-13 20:28

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcalc", "0003_defaultfile_short_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadtrain",
            name="current_time",
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name="uploadtrain",
            name="default_training_file",
            field=models.CharField(
                blank=True,
                choices=[
                    ("english_training_data.txt", "CMU English"),
                    ("english_training_data_onlyA.txt", "CMU English A"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="uploadtrain",
            name="training_model",
            field=models.CharField(default="simple", max_length=128),
        ),
        migrations.AlterField(
            model_name="uploadwithdefault",
            name="training_file",
            field=models.CharField(choices=[], max_length=200),
        ),
        migrations.AlterField(
            model_name="uploadwithdefault",
            name="training_model",
            field=models.CharField(default="simple", max_length=128),
        ),
    ]
