# Generated by Django 5.2.1 on 2025-05-23 07:00

import datetime
import uci_phonotactic_calculator.web.django.webcalc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefaultFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_file", models.FileField(upload_to="default")),
                ("description", models.CharField(max_length=200)),
                ("short_desc", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UploadTrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_file", models.FileField(blank=True, upload_to="uploads")),
                (
                    "default_training_file",
                    models.CharField(
                        blank=True,
                        choices=uci_phonotactic_calculator.web.django.webcalc.models.UploadTrain.get_file_choices,
                        max_length=200,
                    ),
                ),
                ("test_file", models.FileField(upload_to="uploads")),
                ("training_model", models.CharField(default="simple", max_length=128)),
                ("current_time", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="UploadWithDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_file", models.CharField(choices=[], max_length=200)),
                ("test_file", models.FileField(upload_to="uploads")),
                ("training_model", models.CharField(default="simple", max_length=128)),
            ],
        ),
    ]
