# Generated by Django 5.2.3 on 2025-06-23 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webcalc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadtrain",
            name="current_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
